x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.2
  environment:
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__WEBSERVER__SECRET_KEY=secret-key-123
    - API_URL=${API_URL}
    - API_BEARER_TOKEN=${API_BEARER_TOKEN}
    - _PIP_ADDITIONAL_REQUIREMENTS=kafka-python requests python-dotenv
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  networks:
    - data-pipeline

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data-pipeline

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - data-pipeline

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - API_URL=${API_URL}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - CHECKPOINT_LOCATION=${CHECKPOINT_LOCATION}
      - BQ_DATASET=${BQ_DATASET}
      - BQ_TABLE=${BQ_TABLE}

        # GCP Configuration
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_REGION=${GCP_REGION}
      - GCP_SERVICE_ACCOUNT_PATH=${GCP_SERVICE_ACCOUNT_PATH}
        # GCS Buckets
      - GCS_BRONZE_BUCKET=${GCS_BRONZE_BUCKET}
      - GCS_SILVER_BUCKET=${GCS_SILVER_BUCKET}
      - GCS_GOLD_BUCKET=${GCS_GOLD_BUCKET}
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/keys/api-datapipeline-2-ef3107a0390f.json
    ports:
      - "9080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark:/opt/spark/jobs
      - ./jars:/opt/spark/custom_jars
      - ./keys:/opt/spark/keys
    networks:
      - data-pipeline
    depends_on:
      - kafka

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/keys/api-datapipeline-2-ef3107a0390f.json
    volumes:
      - ./spark:/opt/spark/jobs
      - ./jars:/opt/spark/custom_jars
      - ./keys:/opt/spark/keys
    networks:
      - data-pipeline
    depends_on:
      - spark-master

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-pipeline
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy 
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
        echo 'Airflow initialized successfully!'
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully 

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully 

networks:
  data-pipeline:
    driver: bridge

volumes:
  postgres_data: