# docker compose exec spark-master spark://spark-master:7077 /opt/spark/jobs/bronze_writer.py
# docker compose run --rm spark-master --master spark://spark-master:7077 /opt/spark/jobs/streaming/bronze_writer.py
# docker compose exec spark-master spark-submit `
#   --master spark://spark-master:7077 `
#   --deploy-mode client `
#   --conf spark.driver.host=spark-master `
#   --conf spark.driver.bindAddress=0.0.0.0 `
#   --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/spark/config/gcp-service-account.json `
#   --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem `
#   /opt/spark/jobs/streaming/bronze_writer.py

# docker compose exec spark-master /opt/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.23 --conf spark.jars.ivy=/tmp/ivy --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.host=spark-master --conf spark.driver.bindAddress=0.0.0.0 --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/spark/config/gcp-service-account.json --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem /opt/spark/jobs/streaming/bronze_writer.py
# docker compose exec spark-master /opt/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.20 --conf spark.jars.ivy=/tmp/ivy --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.host=spark-master --conf spark.driver.bindAddress=0.0.0.0 --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/spark/config/gcp-service-account.json --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem /opt/spark/jobs/streaming/bronze_writer.py
docker compose exec spark-master /opt/spark/bin/spark-submit --jars /opt/spark/jars/gcs-connector-hadoop3-2.2.6-SNAPSHOT-shaded.jar --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,com.google.cloud.bigdataoss:gcs-connector:hadoop3-2.2.20 --conf spark.jars.ivy=/tmp/ivy --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.host=spark-master --conf spark.driver.bindAddress=0.0.0.0 --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/spark/config/gcp-service-account.json --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.driver.userClassPathFirst=true --conf spark.executor.userClassPathFirst=true --conf spark.hadoop.fs.gs.impl.disable.cache=true --conf spark.jars.excludes=org.slf4j:slf4j-api,org.slf4j:slf4j-log4j12,org.slf4j:slf4j-simple --conf spark.driver.extraJavaOptions=-Dslf4j.simpleLogger.defaultLogLevel=warn --conf spark.executor.extraJavaOptions=-Dslf4j.simpleLogger.defaultLogLevel=warn /opt/spark/jobs/streaming/bronze_writer.py
docker compose exec spark-master /opt/spark/bin/spark-submit --packages com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.35.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 --conf spark.jars.ivy=/tmp/ivy --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.host=spark-master --conf spark.driver.bindAddress=0.0.0.0 /opt/spark/jobs/streaming/bronze_writer.py
docker compose exec spark-master /opt/spark/bin/spark-submit --packages "com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.35.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0" --conf spark.jars.ivy=/tmp/ivy --master spark://spark-master:7077 --deploy-mode client --conf spark.driver.host=spark-master --conf spark.driver.bindAddress=0.0.0.0 /opt/spark/jobs/streaming/bronze_writer.py
# Invoke-WebRequest -Uri "https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-2.2.20-shaded.jar" -OutFile "jars/gcs-connector-shaded.jar"